#!/bin/bash

USAGE='''Commands:
  setupGit
  checkoutGit
  configureGit
  install
  goInstall
  npmInstall
  gitInstall
  yayInstall
  amdGPU
  setClock
    Default: America/Chicago
  sysSetup <hostname> <city>
    defaults: fairytail, Chicago
  createUser <username>
  grubSetup
  bootOrder
  sshKey'''

function userSetup() {
  HOSTNM="${1}"
  CITY="${2}"
  ln -sf /usr/share/zoneinfo/America/${CITY} /etc/localtime
  hwclock --systohc
  echo "LANG=en_US>UTF-8" > /etc/local.conf
  locale-gen
  echo "${HOSTNM}" > /etc/hostname
}

function hostSetup() {
  hostname="${1}"
  HOSTS=$(cat <<-END
127.0.0.1	localhost
::1		localhost
127.0.1.1	${hostname}.localdomain  ${hostname}
END
)
echo "${HOSTS}" >> /etc/hosts
}


case "${1}" in
  "setupGit")
    cd "${HOME}"
    git clone --bare 'https://github.com/nanvenomous/unix.git' "${HOME}/.unx"
    ;;
  "checkoutGit")
    git --git-dir=${HOME}/.unx/ --work-tree=${HOME} checkout
    ;;
  "configureGit")
    git config --global core.excludesfile ~/.gitignore
    git config --global --includes include.path './.keybindings_git'
    git --git-dir=${HOME}/.unx/ --work-tree=${HOME} config --local status.showUntrackedFiles no
    git --git-dir=${HOME}/.unx/ --work-tree=${HOME} config --get remote.origin.fetch
    git --git-dir=${HOME}/.unx/ --work-tree=${HOME} config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    ;;
  "install")
    pacman -Sy $(cat ./rsrc/internal_packages.txt | tr '\n' ' ' )
    ;;
  "goInstall")
    go install github.com/go-task/task/v3/cmd/task@latest
    go install github.com/a-h/templ/cmd/templ@latest
    go install github.com/nanvenomous/e@latest
    go install github.com/nanvenomous/where-to@latest
    go install github.com/moson-mo/pacseek@latest
    ;;
  "npmInstall")
    sudo npm i -g typescript-language-server typescript pyright vscode-langservers-extracted @tailwindcss/language-server
    ;;
  "gitInstall")
    cd ~/.scripts && git clone https://github.com/kutsan/zsh-system-clipboard.git
    mkdir ~/projects
    cd ~/projects
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    curl -fsSL https://bun.sh/install | bash 
    ;;
  "yayInstall")
    yay -S font-symbola enpass-bin
    ;;
  "amdGPU")
    sudo pacman -S ollama-rocm
    sudo pacman -S xf86-video-amdgpu
    sudo pacman -S rocm-opencl-sdk rocm-hip-sdk
    # yay -S opencl-amd
    ;;
  "setClock")
    timedatectl set-ntp true
    timedatectl set-timezone America/Chicago

    sudo systemctl start systemd-timesyncd.service
    sudo systemctl enable systemd-timesyncd.service
    cp rsrc/09-timezone /etc/NetworkManager/dispatcher.d/
    ;;
  "sysSetup")
    hostname="${2}"
    city="${3}"
    userSetup "${hostname:=fairytail}" "${city:=Chicago}"
    hostSetup "${hostname:=fairytail}"

    systemctl enable bluetooth.service
    systemctl enable NetworkManager.service
    systemctl enable systemd-timesyncd.service
    systemctl enable sshd.service
    systemctl --user enable pulseaudio
    amixer sset Master unmute
    passwd

    xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
    ;;
  "createUser")
    username="${2}"
    useradd -m -g users -G wheel "${username}"
    usermod -a -G wheel "${username}"
    passwd "${username}"
    chsh -s /bin/zsh gin
    ;;
  "configUser")
    nvim -c '/wheel' /etc/sudoers
    ;;
  "grubSetup")
    grub-install --target=x86_64-efi --efi-directory=/boot/efi
    grub-mkconfig -o /boot/grub/grub.cfg
    ;;
  "bootOrder")
    efibootmgr -v
    echo "To change the boot order use:"
    echo "efibootmgr -o 0002,0001,0003"
    ;;
  "sshKey")
    ssh-keygen
    echo "now add the key to your github account"
    ;;
  "fromSource")
    cd ~/projects
    git clone https://github.com/nanvenomous/where-to.git
    cd where-to
    make
    sudo make install
    sudo make zsh-completions
    cd ~/projects
    git clone git@github.com:nanvenomous/e.git
    cd e
    make
    sudo make install
    ;;
  *)
    echo "${USAGE}"
    ;;
esac

